/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaVerificacaoPlaca.java
 *
 * Created on 04/11/2011, 15:49:30
 */
package interfacegrafica;

/**
 *
 * @author samuel
 */
public class JanelaVerificacaoPlaca extends javax.swing.JFrame {

    /** Creates new form JanelaVerificacaoPlaca */
    public JanelaVerificacaoPlaca() {
        initComponents();
        rotuloInformacaoBuscaBd.setVisible(false);
        barraDeProgressoVerificacaoPlaca.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rotuloVerificacaoPlaca = new javax.swing.JLabel();
        campoPlacaVerificacaoPlaca = new javax.swing.JTextField();
        botaoCancelarVerificacaoPlaca = new javax.swing.JButton();
        botaoEnviarVerificacaoPlaca = new javax.swing.JButton();
        barraDeProgressoVerificacaoPlaca = new javax.swing.JProgressBar();
        rotuloInformacaoBuscaBd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Verificação Placa"));

        rotuloVerificacaoPlaca.setText("Digite a placa do automóvel que deseja alugar:");

        botaoCancelarVerificacaoPlaca.setText("Cancelar");
        botaoCancelarVerificacaoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarVerificacaoPlacaActionPerformed(evt);
            }
        });

        botaoEnviarVerificacaoPlaca.setText("Enviar");
        botaoEnviarVerificacaoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarVerificacaoPlacaActionPerformed(evt);
            }
        });

        rotuloInformacaoBuscaBd.setText("Verificando no banco de dados:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraDeProgressoVerificacaoPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rotuloVerificacaoPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPlacaVerificacaoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCancelarVerificacaoPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                        .addComponent(botaoEnviarVerificacaoPlaca))
                    .addComponent(rotuloInformacaoBuscaBd))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloVerificacaoPlaca)
                    .addComponent(campoPlacaVerificacaoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(rotuloInformacaoBuscaBd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barraDeProgressoVerificacaoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelarVerificacaoPlaca)
                    .addComponent(botaoEnviarVerificacaoPlaca))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarVerificacaoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarVerificacaoPlacaActionPerformed
        // TODO add your handling code here:
        rotuloInformacaoBuscaBd.setVisible(true);
        barraDeProgressoVerificacaoPlaca.setVisible(true);
        new JanelaCadastroLocacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoEnviarVerificacaoPlacaActionPerformed

    private void botaoCancelarVerificacaoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarVerificacaoPlacaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botaoCancelarVerificacaoPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificacaoPlaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificacaoPlaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificacaoPlaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificacaoPlaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JanelaVerificacaoPlaca().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraDeProgressoVerificacaoPlaca;
    private javax.swing.JButton botaoCancelarVerificacaoPlaca;
    private javax.swing.JButton botaoEnviarVerificacaoPlaca;
    private javax.swing.JTextField campoPlacaVerificacaoPlaca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rotuloInformacaoBuscaBd;
    private javax.swing.JLabel rotuloVerificacaoPlaca;
    // End of variables declaration//GEN-END:variables
}
