/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaVerificacaoCpf.java
 *
 * Created on 04/11/2011, 15:49:16
 */
package interfacegrafica;

/**
 *
 * @author samuel
 */
public class JanelaVerificacaoCpf extends javax.swing.JFrame {

    /** Creates new form JanelaVerificacaoCpf */
    public JanelaVerificacaoCpf() {
        initComponents();
        rotuloBuscaBd.setVisible(false);
        barraProgressoVerificaCpf.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rotuloVerificaCpf = new javax.swing.JLabel();
        campoVerificaCpf = new javax.swing.JTextField();
        botaoCancelarVerificaCpf = new javax.swing.JButton();
        botaoEnviarVerificaCpf = new javax.swing.JButton();
        barraProgressoVerificaCpf = new javax.swing.JProgressBar();
        rotuloBuscaBd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Verificação do CPF:"));

        rotuloVerificaCpf.setText("Cpf:");

        botaoCancelarVerificaCpf.setText("Cancelar");
        botaoCancelarVerificaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarVerificaCpfActionPerformed(evt);
            }
        });

        botaoEnviarVerificaCpf.setText("Verificar");
        botaoEnviarVerificaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarVerificaCpfActionPerformed(evt);
            }
        });

        rotuloBuscaBd.setText("Buscando no banco de dados:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraProgressoVerificaCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(rotuloBuscaBd)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCancelarVerificaCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addComponent(botaoEnviarVerificaCpf))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rotuloVerificaCpf)
                        .addGap(17, 17, 17)
                        .addComponent(campoVerificaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoVerificaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotuloVerificaCpf))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEnviarVerificaCpf)
                    .addComponent(botaoCancelarVerificaCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(rotuloBuscaBd)
                .addGap(18, 18, 18)
                .addComponent(barraProgressoVerificaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarVerificaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarVerificaCpfActionPerformed
        barraProgressoVerificaCpf.setVisible(true);
        rotuloBuscaBd.setVisible(true);
        barraProgressoVerificaCpf.setMaximum(100);
        new JanelaVerificacaoPlaca().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoEnviarVerificaCpfActionPerformed

    private void botaoCancelarVerificaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarVerificaCpfActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_botaoCancelarVerificaCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificacaoCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificacaoCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificacaoCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaVerificacaoCpf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JanelaVerificacaoCpf().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgressoVerificaCpf;
    private javax.swing.JButton botaoCancelarVerificaCpf;
    private javax.swing.JButton botaoEnviarVerificaCpf;
    private javax.swing.JTextField campoVerificaCpf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rotuloBuscaBd;
    private javax.swing.JLabel rotuloVerificaCpf;
    // End of variables declaration//GEN-END:variables
}
